### ISSUE TITLE
ValueError: None values not supported.   tf10.0

### ISSUE THREAD

**Issue by pannous** [ry/tensorflow-resnet#14]
```
Filling queue with 20000 CIFAR images before starting to train. This will take a few minutes.
Traceback (most recent call last):
  File "train_cifar.py", line 311, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "train_cifar.py", line 307, in main
    train(is_training, logits, images, labels)
  File "/home/me/tensorflows/tensorflow-resnet/resnet_train.py", line 33, in train
    loss_ = loss(logits, labels)
  File "/home/me/tensorflows/tensorflow-resnet/resnet.py", line 148, in loss
    cross_entropy = tf.nn.sparse_softmax_cross_entropy_with_logits(logits, labels)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 545, in sparse_softmax_cross_entropy_with_logits
    logits = ops.convert_to_tensor(logits)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 621, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 180, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 163, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 346, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.
```

**Comment by andyhahaha** [comment]
I have this problem too.

**Comment by deepxiangfa** [comment]
I also have this problem.

**Comment by onlytailei** [comment]
How to solve it?

**Comment by zzks** [comment]
how to fix it?
downgrade TF to 7?

**Comment by ymzhang1919** [comment]
To fix the error, just modify Line 104 in resnet.py to "return inference_small_config(x, c)"
