### ISSUE TITLE
Bug in forward.py

### ISSUE THREAD

**Issue by omidme** [ry/tensorflow-resnet#31]
Hello,
Thanks for this work.
the following error occurred when I execute the forward.py file

Traceback (most recent call last):
  File "forward.py", line 11, in <module>
    new_saver.restore(sess, [checkpoint_fn(layers)])
  File "/home/msf/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1428, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/msf/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/msf/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 944, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1,) for Tensor u'save/Const:0', which has shape '()'

Could you please help me?

Thanks much!
Omid

**Comment by hhxjzyr** [comment]
@omidme I encountered the same issue , How did you fix it? plaease

**Comment by xianefeng** [comment]
@hhxjzyr copy the pretrained .ckpt .meta to the folder of forward.py
